### ISSUE TITLE
Error on exercise 09 in chapter 03

### ISSUE THREAD

**Issue by zamatta** [ivanpop/CS-for-Dummies#4]
The condition below seems to be incorrect.             
```
bool isOutsideRectangle = (x < -1 && x > 5 && y < 1 && y > 5) ? true : false;
```
how can `x = -2` will `x < -1 && x > 5` at the same time.

The correct condition is:

```
bool isOutsideRectangle = (x < -1 || x > 5) && (y < 1 || y > 5) ? true : false;
```

**Comment by ivanpop** [comment]
Yes. You're condition is the correct one.
